name: CD

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker build $PWD -t chat:chat
    - name: Stop
      run: ./../../stop
    - name: Clean up
      run: ./../../cleanup
    - name: Run
      run: RUNNER_TRACKING_ID="" && ./../../run
