name: CD

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Pull changes
      run: git pull
    - name: Stop docker
      run: docker stop chat
    - name: Clear docker
      run: docker rmi -f chat
    - name: Build docker
      run: docker build $PWD -t chat
    - name: Run
      run: docker run -it --rm --name chat chat
