name: CD

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Pull changes
      run: git pull
    - name: Stop
      run: docker stop chat; docker rm chat
    - name: Build
      run: docker build $PWD -t chat
    - name: Clean up
      run: ./cleanup
    - name: Run
      run: docker run -it --rm --name chat chat:chat
