name: CD

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Pull changes
      run: git pull
    - name: Stop docker
      run: sudo docker stop chat
    - name: Clear docker
      run: sudo docker rmi -f chat
    - name: Build docker
      run: sudo docker build $PWD -t chat
    - name: Run
        run: sudo docker run -it --rm --name chat chat
