name: CD

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: docker images
    - name: Pull changes
      run: git pull
    - name: Stop
      run: ./../../stop
    - name: Build
      run: docker build $PWD -t chat:chat
    - name: Clean up
      run: ./../../cleanup
    - name: Run
      run: docker run -p 80:8000/tcp --rm --name chat chat:chat
